### PR TITLE
[WIP] Init AdGuard Home section

### PR DESCRIPTION
**Pull request by kmunk1975**
Adding the AdGuard Home section.

Updates https://github.com/AdguardTeam/AdGuardHome/issues/5013

### CODE REVIEW

**Comment by ameshkov** [comment]
Let's start with moving the first article (Getting Started): https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started

Note, that you can access the original markdown files of the Github Wiki by cloning this repo:
https://github.com/AdguardTeam/AdGuardHome.wiki.git

**Comment by kmunk1975** [comment]
If  only using 1.22.19 when clone, install/start and build them, i have to make a virtualbox, with ubuntu only with the old version of 
github, node.js and  commands.

On my windows pc i will use  3.4.2 (4.0) latest stable ! Yarn says migration are best and give new options for program/ package.
I have all other (github, node.js and  terminal) newest on updated win11.

I update and learn the new commands  yarn latest stable.

**Comment by kmunk1975** [comment]
GitHub - AdguardTeam/KnowledgeBaseDNS: AdGuard DNS knowledge base

 We cloned and build AdGuard DNS knowledge base(wiki) to move it.
https://adguardteam.github.io/KnowledgeBaseDNS/ 

Now its adguardhome(wiki) get started,        
https://github.com/AdguardTeam/AdGuardHome/ [Screenshot_20221017-191747_Chrome.jpg](https://user-images.githubusercontent.com/89806216/196241805-c8ba6c2c-99f0-4be6-b5f0-cfd5f0936260.jpg)


Are both the same task and same wiki / code? But different PR?

**Comment by kmunk1975** [comment]
> > i have to make a virtualbox
> 
> Hi! You may also consider using [WSL](https://learn.microsoft.com/en-us/windows/wsl/) with Ubuntu package. While it will take some time to install and configure it, around a day I guess, it's a nice way to have Linux under Widows with a set of advantages like having a nice [VS code integration](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode). Works pretty fine on Windows 10, not sure about Windows 11 though.

In in my win 11. Wsl 2 sub system. I will do.

**Comment by ameshkov** [comment]
Run `git clone https://github.com/AdguardTeam/AdGuardHome.wiki.git` to download the markdown content of the GH wiki.

**Comment by kmunk1975** [comment]
Hope the best for adguardteam, i have dropped out of openhack and stopped doing pr, for your team, and dont do other project under Openhack.

Primary because of i have to use time with family and friends, and because adguardteam and I, dont seem to agreed on errors and i wait or use to much time until now, without I do your task.
Thanks for help. But i stop today.
Kristian

**Pull request closed without merging**
