### PR TITLE
dns-providers.md

### PR DESCRIPTION
**Pull request by MangOleh22**

### CODE REVIEW

**Comment by anastasiia-fedotova** [comment]
Hello! Please move your DNS service information to the Small personal resolvers section and alphabetize it.

**Review by anastasiia-fedotova — CHANGES_REQUESTED** [review]
Hello! Please move your DNS service information to the Small personal resolvers section and alphabetize it.

**Comment by tina-hello** [comment]
The link is dead and the DoH server isn't responding

**Comment by anastasiia-fedotova** [comment]
Unfortunately, due to the lack of a response and because the link in the pull request doesn't work, I have to close it.

**Pull request closed without merging**
